version: '3'

services:

  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
    ports:
      - "127.0.0.1:9300:9300"
      - "127.0.0.1:9200:9200"
    environment:
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.2
    ports:
      - "127.0.0.1:5601:5601"
    environment:
      - SERVER_NAME=kibana
      - ELASTICSEARCH_URL=http://elastic-search:9200