
Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/xenial64"

    # Resource limits

    config.vm.provider "virtualbox" do |machine|
        machine.memory = 1024
        machine.cpus = 1
    end

    # Public key for accessing guest machine over SSH via Ansible

    config.vm.provision "file",
        source: "~/.ssh/id_rsa.pub",
        destination: "/home/vagrant/host_key.pub"

    config.vm.provision "shell",
        inline: "cat /home/vagrant/host_key.pub >> /home/vagrant/.ssh/authorized_keys"

    config.vm.provision "shell",
        inline: "rm /home/vagrant/host_key.pub"

    # Network settings

    config.vm.network "private_network", ip: "192.168.3.11"

end