---
- name: install docker
  block:

    - name: install docker prerequisites
      apt:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages: "{{ docker_prerequisite_packages }}"

    - name: add docker gpg key
      apt_key:
        url: "{{ docker_gpg_key_url }}"
        state: present

    - name: add docker repository
      apt_repository:
        repo: "{{ docker_repository }}"
        state: present
      become: yes

    - name: install docker package
      apt:
        name: docker-ce

    - name: add user to docker group
      user:
        name: "{{ user_for_docker_group }}"
        groups: docker
      when: add_user_to_docker_group

  become: yes