---
- name: install docker prerequisites
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
  become: yes

- name: add docker gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: add docker repository
  apt_repository:
    repo: >-
          deb [arch=amd64]
          https://download.docker.com/linux/ubuntu
          {{ ansible_distribution_release }} stable
    state: present
  become: yes

- name: install docker package
  apt:
    name: docker-ce
  become: yes