version: '3'

services:

  prometheus:
    image: prom/prometheus:v2.17.1
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:6.7.1
    ports:
      - "127.0.0.1:3000:3000"